<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
	Command descriptor document
-->
<!DOCTYPE commands [
	<!ELEMENT commands (command+)>
	<!-- Command descriptor -->
	<!ELEMENT command (alias*, argument*, option*, flag*)>
	<!-- 
		name: command name
		impl: implementor class name
		description: ResourceBundle key
	-->
	<!ATTLIST command 
	name NMTOKEN #REQUIRED 
	impl NMTOKEN #IMPLIED 
	description CDATA #IMPLIED >

	<!--
		name: alias name
	-->
	<!ELEMENT alias EMPTY>
	<!ATTLIST alias
		name NMTOKEN #REQUIRED>

	<!--
		name: option name
		command-attribute: Command property
		position: argument name
		arg-name: argument name
		required: required flag
		value: option default value (used for non required arguments)
		description: argument description [optional] if not specified [command name].[option name] is assumed
	-->
	<!ELEMENT option EMPTY>
	<!ATTLIST option 
		name NMTOKEN #REQUIRED 
		command-attribute NMTOKEN #IMPLIED 
		arg-name CDATA #IMPLIED
		required NMTOKEN #IMPLIED 
		value CDATA #IMPLIED 
		description CDATA #IMPLIED>

	<!ELEMENT argument EMPTY>
	<!ATTLIST argument  
		name NMTOKEN #REQUIRED 
		position NMTOKEN #REQUIRED 
		arg-name CDATA #IMPLIED
		command-attribute NMTOKEN #IMPLIED 
		required NMTOKEN #IMPLIED 
		value CDATA #IMPLIED 
		description CDATA #IMPLIED>

	<!ELEMENT flag EMPTY>
	<!ATTLIST flag
		name NMTOKEN #REQUIRED 
		command-attribute NMTOKEN #IMPLIED 
		description CDATA #IMPLIED>
		
	]>
	
<commands>
	
	<command name="addmixin" impl="org.apache.jackrabbit.chain.command.AddMixin">
		<alias name="addmix"/>
		<argument 
			name="path" 
			position="0"
			arg-name="jcr.path" 
			description="jcr.path"
			required="true"/>
		<argument 
			name="mixin"
			position="1" 
			arg-name="mixin.name" 
			command-attribute="mixinName"
			required="true"/>
	</command>	
	
	<command name="addnode" impl="org.apache.jackrabbit.chain.command.AddNode">
		<alias name="add"/>
		<argument 
			name="name" 
			position="0"
			arg-name="node name" 
			command-attribute="nodeName" 
			description="node.name" 
			required="true"/>
		<argument 
			name="type"
			position="1" 
			arg-name="node type" 
			command-attribute="nodeType" 
			description="node.type" />
	</command>	
		
	<command name="clearworkspace" impl="org.apache.jackrabbit.chain.command.ClearWorkspace"/>
	
	<command name="copy" impl="org.apache.jackrabbit.chain.command.Copy">
		<argument 
			name="from" 
			position="0" 
			arg-name="jcr.path" 
			description="copy.from"
			required="true"/>
		<argument 
			name="to" 
			position="1" 
			arg-name="jcr.path" 
			description="copy.to"
			required="true"/>
	</command>
	
	<command name="connect" impl="org.apache.jackrabbit.chain.command.ConnectToRmiServer">
		<argument 
			name="url" 
			position="0" 
			arg-name="url" 
			required="true"/>
	</command>
		
	<command name="currentnode" impl="org.apache.jackrabbit.chain.command.CurrentNode">
		<alias name="cd"/>
		<alias name="cn"/>
		<argument 
			name="path" 
			position="0"
			arg-name="path" 
			description="node.path"/>
	</command>	

	<command name="exportdocview" impl="org.apache.jackrabbit.chain.command.xml.ExportDocViewToFile">
		<alias name="exportdoc"/>
		<argument 
			name="from" 
			position="0"
			arg-name="jcr.path" 
			description="exportview.from"
			required="true"/>
		<argument 
			name="to" 
			position="1"
			arg-name="fs.path" 
			description="exportview.to"
			required="true"/>
		<flag 
			name="overwrite" 
			description="overwrite"/>
		<flag
			name="skipBinary" 
			description="exportview.skipBinary" />
		<flag 
			name="noRecurse" 
			description="exportview.noRecurse"/>
	</command>	

	<command name="exportfilesystem" impl="org.apache.jackrabbit.chain.command.fs.ExportFileSystem">
		<alias name="exportfs"/>
		<argument 
			name="from"
			position="0" 
			arg-name="jcr.path" 
			description="source"
			required="true"/>
		<argument 
			name="to" 
			position="1"
			arg-name="fs.path" 
			description="destination"
			required="true"/>
		<flag name="overwrite"/>
	</command>	
	
	<command name="exportproperty" impl="org.apache.jackrabbit.chain.command.fs.ExportPropertyToFile">
		<alias name="exportprop"/>
		<alias name="exportp"/>
		<argument 
			name="name"
			position="0" 
			arg-name="name" 
			description="name" 
			required="true"/>
		<argument 
			name="to" 
			position="1"
			arg-name="fs.path" 
			required="true"/>
		<option 
			name="idx" 
			arg-name="index" 
			command-attribute="index"/>
		<flag 
			name="overwrite" 
			description="overwrite"/>
	</command>				
	
	<command name="exportsysview" impl="org.apache.jackrabbit.chain.command.xml.ExportSysViewToFile">
		<alias name="exportsys"/>
		<argument 
			name="from" 
			position="0"
			arg-name="jcr.path" 
			description="exportview.from"
			required="true"/>
		<argument 
			name="to" 
			position="1"
			arg-name="fs.path" 
			description="exportview.to"
			required="true"/>
		<flag 
			name="overwrite" 
			description="overwrite"/>
		<flag 
			name="skipBinary" 
			description="exportview.skipBinary" />
		<flag 
			name="noRecurse" 
			description="exportview.noRecurse"/>
	</command>	
	
	<command name="importfilesystem" impl="org.apache.jackrabbit.chain.command.fs.ImportFileSystem">
		<alias name="importfs"/>
		<argument 
			name="from"
			position="0" 
			arg-name="file" 
			description="file" 
			required="true"/>
	</command>		

	<command name="importxml" impl="org.apache.jackrabbit.chain.command.xml.ImportXmlFromFile">
		<argument 
			name="from" 
			position="0"
			arg-name="file" 
			description="file" 
			required="true"/>
		<argument 
			name="uuidBehaviour" 
			position="1"
			arg-name="int"/>
	</command>			
		
	<command name="login" impl="org.apache.jackrabbit.chain.command.Login">
		<option 
			name="u" 
			command-attribute="user"
			arg-name="user name"/>
		<option 
			name="p"
			command-attribute="password" 
			arg-name="password"/>
		<option 
			name="w" 
			command-attribute="workspace" 			
			arg-name="workspace" />
	</command>
	
	<command name="logout" impl="org.apache.jackrabbit.chain.command.Logout"/>
	
	<command name="lsitems">
		<alias name="ls"/>
		<argument 
			name="pattern" 
			command-attribute="patternKey"
			position="0"
			arg-name="name pattern" />
		<option 
			name="maxitems" 
			arg-name="int" 
			description="show.max.items"/>
	</command>
	
	<command name="lscollect">
		<alias name="collect"/>
		<argument name="pattern" position="0" arg-name="name.pattern" required="true"/>
		<option name="depth" arg-name="var.name" value="1"/>
		<option 
			name="maxitems" 
			arg-name="int" 
			description="show.max.items"/>
	</command>	
	
	<command name="lsproperties" >
		<alias name="lsp"/>
		<alias name="lsprop"/>
		<argument 
			name="pattern" 
			position="0"
			arg-name="name.pattern" 
			description="ls.pattern"/>
		<option 
			name="maxitems" 
			arg-name="int" 
			description="show.max.items"/>
	</command>		

	<command name="lscollectproperties">
		<alias name="collectp"/>
		<alias name="collectprop"/>
		<argument name="pattern" position="0" arg-name="name.pattern" required="true"/>
		<option name="depth" arg-name="var.name" value="1"/>
		<option 
			name="maxitems" 
			arg-name="int" 
			description="show.max.items"/>
	</command>	
		
	<command name="lsnodes" >
		<alias name="lsn"/>
		<argument 
			name="pattern" 
			position="0"
			arg-name="name.namepattern" 
			description="lsitems.pattern"/>
		<option 
			name="maxitems" 
			arg-name="int" 
			description="show.max.items"/>
		<flag name="path" description="lsnodes.path"/>
		<flag name="uuid" description="lsnodes.uuid"/>
		<flag name="m" description="lsnodes.m"/>
		<flag name="nsize" description="lsnodes.nsize"/>
		<flag name="psize" description="lsnodes.psize"/>
		<flag name="rsize" description="lsnodes.rsize"/>
		<flag name="v" description="lsnodes.v"/>
		<flag name="l" description="lsnodes.l"/>
		<flag name="r" description="lsnodes.r"/>
		<flag name="locked" description="lsnodes.locked"/>
		<flag name="hasLock" description="lsnodes.hasLock"/>
		<flag name="new" description="lsnodes.new"/>
		<flag name="mod" description="lsnodes.mod"/>
	</command>	

	<command name="lscollectnodes">
		<alias name="lscollectn"/>
		<alias name="collectn"/>
		<argument name="pattern" position="0" arg-name="name.pattern" required="true"/>
		<option name="depth" arg-name="var.name" value="1"/>
		<option 
			name="maxitems" 
			arg-name="int" 
			description="show.max.items"/>
		<flag name="uuid" description="lsnodes.uuid"/>
		<flag name="nsize" description="lsnodes.nsize"/>
		<flag name="psize" description="lsnodes.psize"/>
		<flag name="rsize" description="lsnodes.rsize"/>
		<flag name="m" description="lsnodes.m"/>
		<flag name="v" description="lsnodes.v"/>
		<flag name="l" description="lsnodes.l"/>
		<flag name="r" description="lsnodes.r"/>
		<flag name="locked" description="lsnodes.locked"/>
		<flag name="hasLock" description="lsnodes.hasLock"/>
		<flag name="new" description="lsnodes.new"/>
		<flag name="mod" description="lsnodes.mod"/>
		<flag name="path" description="lsnodes.path"/>
	</command>	

	<command name="lsreferences" impl="org.apache.jackrabbit.chain.command.info.LsReferences">
		<alias name="lsr"/>
		<alias name="lsref"/>
		<argument 
			name="path" 
			position="0"
			arg-name="jcr.path" 
			description="jcr.path"
			required="true"/>
	</command>
	
	<command name="move" impl="org.apache.jackrabbit.chain.command.Move">
		<argument 
			name="from" 
			arg-name="jcr.path" 
			position="0" 
			description="move.from"
			required="true"/>
		<argument 
			name="to" 
			arg-name="jcr.path" 
			position="1" 
			description="move.to"
			required="true"/>
	</command>
	
	<command name="refresh" impl="org.apache.jackrabbit.chain.command.Refresh">
		<argument 
			name="path" 
			arg-name="jcr.path"
			position="0"/>
		<flag name="keepChanges"/>
	</command>
	
	<command name="removeitem" impl="org.apache.jackrabbit.chain.command.RemoveItem">
		<alias name="remove"/>
		<alias name="delete"/>
		<alias name="rm"/>
		<alias name="del"/>
		<argument 
			name="path"
			position="0" 
			arg-name="path" 
			description="path"/>
	</command>		

	<command name="removeitems" impl="org.apache.jackrabbit.chain.command.RemoveItems">
		<alias name="rmitems"/>
		<alias name="delitems"/>
		<argument 
			name="pattern" 
			position="0"
			arg-name="pattern" 
			description="pattern" 
			required="true"/>
	</command>		

	<command name="removemixin" impl="org.apache.jackrabbit.chain.command.RemoveMixin">
		<alias name="removemix"/>
		<alias name="rmmix"/>
		<alias name="delmix"/>
		<argument 
			name="path" 
			position="0"
			arg-name="jcr.path" 
			description="jcr.path" 
			required="true"/>
		<argument 
			name="mixin"
			position="1" 
			arg-name="mixin.name" 
			command-attribute="mixinName"
			description="mixin.name"
			required="true"/>
	</command>	

	<command name="rename" impl="org.apache.jackrabbit.chain.command.Rename">
		<argument 
			name="from" 
			position="0" 
			arg-name="name" 
			description="rename.from"
			required="true"/>
		<argument 
			name="to" 
			position="1" 
			arg-name="name" 
			description="rename.to"
			required="true"/>
	</command>
	
	<command name="save" impl="org.apache.jackrabbit.chain.command.SaveSession"/>		

	<command name="savenode" impl="org.apache.jackrabbit.chain.command.SaveNode"/>		
	
	<command name="setmultivalueproperty" impl="org.apache.jackrabbit.chain.command.SetMultivalueProperty">
		<alias name="setmultiprop"/>
		<argument 
			name="name" 
			position="0"
			arg-name="name" 
			command-attribute="propertyName"
			description="setProp.name" 
			required="true"/>
		<argument 
			name="value" 
			position="1"
			arg-name="value" 
			description="setProp.value" 
			required="true"/>
		<option 
			name="type" 
			arg-name="type" 
			description="setProp.type" 
			command-attribute="propertyType" />
		<option 
			name="regexp" 
			command-attribute="regExp"
			arg-name="regular expression"/>
	</command>		
		
	<command name="setproperty" impl="org.apache.jackrabbit.chain.command.SetProperty">
		<alias name="setprop"/>
		<argument 
			name="name" 
			position="0"
			arg-name="name" 
			command-attribute="propertyName"
			required="true"/>
		<argument 
			name="value" 
			position="1"
			arg-name="value" 
			required="true"/>
		<option 
			name="type" 
			arg-name="type" 
			command-attribute="propertyType" />
	</command>	

	<command name="setpropertyfromfile" impl="org.apache.jackrabbit.chain.command.fs.SetPropertyFromFile">
		<alias name="setpropfromfile"/>
		<argument 
			name="name" 
			position="0"
			arg-name="name" 
			command-attribute="propertyName"
			description="setProp.name" 
			required="true"/>
		<argument 
			name="path" 
			position="1"
			arg-name="path" 
			command-attribute="value" 
			required="true"/>
		<option 
			name="type" 
			arg-name="type" 
			description="setProp.type" 
			command-attribute="propertyType" />
	</command>		

	<command name="sqlquery">
		<alias name="sql"/>
		<argument 
			name="statement" 
			position="0"
			arg-name="stmt" 
			required="true"/>
		<option 
			name="maxitems" 
			arg-name="int" 
			description="show.max.items"/>
		<flag name="uuid" description="lsnodes.uuid"/>
		<flag name="nsize" description="lsnodes.nsize"/>
		<flag name="psize" description="lsnodes.psize"/>
		<flag name="rsize" description="lsnodes.rsize"/>
		<flag name="m" description="lsnodes.m"/>
		<flag name="v" description="lsnodes.v"/>
		<flag name="l" description="lsnodes.l"/>
		<flag name="r" description="lsnodes.r"/>
		<flag name="locked" description="lsnodes.locked"/>
		<flag name="hasLock" description="lsnodes.hasLock"/>
		<flag name="new" description="lsnodes.new"/>
		<flag name="mod" description="lsnodes.mod"/>
		<flag name="path" description="lsnodes.path"/>		
	</command>
	
	<command name="startjackrabbit" 
		impl="org.apache.jackrabbit.chain.command.StartJackrabbit">
		<option 
			name="config" 
			arg-name="file" 
			required="true"/>
		<option 
			name="home" 
			arg-name="folder" 
			required="true"/>
	</command>
	
	<command name="stopjackrabbit" 
		impl="org.apache.jackrabbit.chain.command.StopJackrabbit" />

	<!-- info commands -->
	<command name="help" impl="org.apache.jackrabbit.chain.command.info.Help">
		<argument 
			name="command" 
			position="0"
			arg-name="command name" 
			required="false" />
	</command>
	
	<command name="cat" impl="org.apache.jackrabbit.chain.command.info.Cat">
		<argument name="path" position="0" arg-name="path" required="true"/>
		<argument name="idx" position="1" arg-name="index" command-attribute="index"/>
	</command>	
	
	<command name="dump" impl="org.apache.jackrabbit.chain.command.info.Dump"/>	
	
	<!-- script -->
	<command name="source" impl="org.apache.jackrabbit.chain.cli.SourceCommand">
		<argument name="file" position="0" arg-name="fs.path" required="true"/>
	</command>

	<command name="xpathquery">
		<alias name="xpath"/>
		<argument 
			name="statement" 
			position="0"
			arg-name="stmt" 
			required="true"/>
		<option 
			name="maxitems" 
			arg-name="int" 
			description="show.max.items"/>
		<flag name="uuid" description="lsnodes.uuid"/>
		<flag name="nsize" description="lsnodes.nsize"/>
		<flag name="psize" description="lsnodes.psize"/>
		<flag name="rsize" description="lsnodes.rsize"/>
		<flag name="m" description="lsnodes.m"/>
		<flag name="v" description="lsnodes.v"/>
		<flag name="l" description="lsnodes.l"/>
		<flag name="r" description="lsnodes.r"/>
		<flag name="locked" description="lsnodes.locked"/>
		<flag name="hasLock" description="lsnodes.hasLock"/>
		<flag name="new" description="lsnodes.new"/>
		<flag name="mod" description="lsnodes.mod"/>
		<flag name="path" description="lsnodes.path"/>		
	</command>

</commands>