<?xml version="1.0" encoding="UTF-8"?>
<!--
<!DOCTYPE config [
        <!ELEMENT config ((collection | noncollection)? , filter?) >

        <!ELEMENT collection (nodetypes) >
        <!ELEMENT noncollection (nodetypes) >

        <!ELEMENT filter (class, namespaces?, nodetypes?) >

        <!ELEMENT class >
        <!ATTLIST class
            name  CDATA #REQUIRED
        >
        <!ELEMENT namespaces (prefix | uri)* >
        <!ELEMENT prefix (CDATA) >
        <!ELEMENT uri (CDATA) >

        <!ELEMENT nodetypes (nodetype)* >
        <!ELEMENT nodetype (CDATA) >
]>
-->

<config>
    <!--
    Defines nodetypes, that should always be displayed as 'collection'.
    -->
    <!--
    <collection>
        <nodetypes>
            <nodetype>nt:folder</nodetype>
        </nodetypes>
    </collection>
    -->
    <!--
    Define nodetypes, that should never by displayed as 'collection'
    -->
    <noncollection>
        <nodetypes>
            <nodetype>nt:file</nodetype>
            <nodetype>nt:resource</nodetype>
        </nodetypes>
    </noncollection>
    <!--
     Filter that allows to prevent certain items from being displayed.
     Please note, that this has an effect on PROPFIND calls only and does not
     provide limited access to those items matching any of the filters.

     However specifying a filter may cause problems with PUT or MKCOL if the
     resource to be created is being filtered out, thus resulting in inconsistent
     responses (e.g. PUT followed by PROPFIND on parent).
     -->
    <filter>
        <!-- class element defines the resource filter to be used. The specified class
             must implement the ResourceFilter interface -->
        <class name="org.apache.jackrabbit.webdav.simple.DefaultResourceFilter" />
        <!-- Nodetype names to be used to filter child nodes.
             A child node can be filtered if the declaring nodetype of its definition
             is one of the nodetype names specified in the nodetypes Element.
             E.g. defining 'rep:root' as filtered nodetype whould result in jcr:system
             being hidden but no other child node of the root node, since those
             are defined by the nodetype nt:unstructered.
        -->
        <!--
        <nodetypes>
            <nodetype>rep:root</nodetype>
        </nodetypes>
        -->
        <!-- Namespace prefixes or uris. Items having a name that matches any of the
             entries will be filtered.
        -->
        <namespaces>
            <prefix>rep</prefix>
            <prefix>jcr</prefix>
            <!--
            <uri>internal</uri>
            <uri>http://www.jcp.org/jcr/1.0</uri>
            -->
        </namespaces>
    </filter>
</config>

